module p_4_fibo;

typedef struct {
  logic [11:0] csr_index;  
  logic [31:0] csr_result; 
} csr_t;

typedef struct {
  // INSN
  logic [31:0] pc;     
  logic [31:0] opcode;    
  string asm;        
  // X
  logic [4:0] xreg_index;
  logic [31:0] xreg_result;    
  // F
  logic [4:0] freg_index;
  logic [31:0] freg_result; 
  // V
  logic [4:0] vreg_index;
  logic [127:0] vreg_result;
  // CSR
  csr_t csr_list[8]; // Dynamic array
} instruction_t;
    

    // Associative array to store instructions by order
instruction_t instruction_array [0:86];
    
initial begin
  instruction_array[0]  = '{asm: "auipc   t0, 0x0"                 , pc: 'h00001000  , opcode: 'h00000297  , xreg_index: 'd5       , xreg_result: 'h00001000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[1]  = '{asm: "addi    a1, t0, 32"              , pc: 'h00001004  , opcode: 'h02028593  , xreg_index: 'd11      , xreg_result: 'h00001020, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[2]  = '{asm: "csrr    a0, mhartid"             , pc: 'h00001008  , opcode: 'hf1402573  , xreg_index: 'd10      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[3]  = '{asm: "lw      t0, 24(t0)"              , pc: 'h0000100c  , opcode: 'h0182a283  , xreg_index: 'd5       , xreg_result: 'h80000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[4]  = '{asm: "jr      t0"                      , pc: 'h00001010  , opcode: 'h00028067  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[5]  = '{asm: "auipc   t0, 0x0"                 , pc: 'h80000000  , opcode: 'h00000297  , xreg_index: 'd5       , xreg_result: 'h80000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[6]  = '{asm: "addi    t0, t0, 128"             , pc: 'h80000004  , opcode: 'h08028293  , xreg_index: 'd5       , xreg_result: 'h80000080, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[7]  = '{asm: "lw      t1, 0(t0)"               , pc: 'h80000008  , opcode: 'h0002a303  , xreg_index: 'd6       , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[8]  = '{asm: "slti    t2, t1, 2"               , pc: 'h8000000c  , opcode: 'h00232393  , xreg_index: 'd7       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[9]  = '{asm: "beqz    t2, pc + 20"             , pc: 'h80000010  , opcode: 'h00038a63  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[10] = '{asm: "add     t2, zero, zero"          , pc: 'h80000024  , opcode: 'h000003b3  , xreg_index: 'd7       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[11] = '{asm: "li      t3, 1"                   , pc: 'h80000028  , opcode: 'h00100e13  , xreg_index: 'd28      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[12] = '{asm: "li      t4, 2"                   , pc: 'h8000002c  , opcode: 'h00200e93  , xreg_index: 'd29      , xreg_result: 'h00000002, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[13] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[14] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[15] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[16] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[17] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[18] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000003, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[19] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[20] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[21] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[22] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000002, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[23] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[24] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000002, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[25] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000004, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[26] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[27] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[28] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[29] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000003, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[30] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000002, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[31] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000003, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[32] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000005, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[33] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[34] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[35] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[36] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000005, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[37] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000003, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[38] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000005, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[39] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000006, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[40] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[41] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[42] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[43] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000008, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[44] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000005, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[45] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000008, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[46] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000007, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[47] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[48] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[49] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[50] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h0000000d, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[51] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000008, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[52] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h0000000d, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[53] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000008, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[54] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[55] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[56] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[57] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000015, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[58] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h0000000d, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[59] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000015, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[60] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h00000009, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[61] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[62] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[63] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[64] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000022, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[65] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000015, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[66] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000022, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[67] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[68] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[69] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[70] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[71] = '{asm: "add     t6, t2, t3"              , pc: 'h8000003c  , opcode: 'h01c38fb3  , xreg_index: 'd31      , xreg_result: 'h00000037, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[72] = '{asm: "add     t2, t3, zero"            , pc: 'h80000040  , opcode: 'h000e03b3  , xreg_index: 'd7       , xreg_result: 'h00000022, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[73] = '{asm: "add     t3, t6, zero"            , pc: 'h80000044  , opcode: 'h000f8e33  , xreg_index: 'd28      , xreg_result: 'h00000037, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[74] = '{asm: "addi    t4, t4, 1"               , pc: 'h80000048  , opcode: 'h001e8e93  , xreg_index: 'd29      , xreg_result: 'h0000000b, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[75] = '{asm: "j       pc - 0x1c"               , pc: 'h8000004c  , opcode: 'hfe5ff06f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[76] = '{asm: "slt     t5, t1, t4"              , pc: 'h80000030  , opcode: 'h01d32f33  , xreg_index: 'd30      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[77] = '{asm: "beqz    t5, pc + 8"              , pc: 'h80000034  , opcode: 'h000f0463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[78] = '{asm: "j       pc + 0x18"               , pc: 'h80000038  , opcode: 'h0180006f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[79] = '{asm: "auipc   t0, 0x0"                 , pc: 'h80000050  , opcode: 'h00000297  , xreg_index: 'd5       , xreg_result: 'h80000050, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[80] = '{asm: "addi    t0, t0, 52"              , pc: 'h80000054  , opcode: 'h03428293  , xreg_index: 'd5       , xreg_result: 'h80000084, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[81] = '{asm: "sw      t3, 0(t0)"               , pc: 'h80000058  , opcode: 'h01c2a023  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[82] = '{asm: "li      t0, 1"                   , pc: 'h8000005c  , opcode: 'h00100293  , xreg_index: 'd5       , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[83] = '{asm: "auipc   t1, 0x0"                 , pc: 'h80000060  , opcode: 'h00000317  , xreg_index: 'd6       , xreg_result: 'h80000060, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[84] = '{asm: "addi    t1, t1, 96"              , pc: 'h80000064  , opcode: 'h06030313  , xreg_index: 'd6       , xreg_result: 'h800000c0, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[85] = '{asm: "sw      t0, 0(t1)"               , pc: 'h80000068  , opcode: 'h00532023  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[86] = '{asm: "j       pc + 0x0"                , pc: 'h8000006c  , opcode: 'h0000006f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
end

endmodule
