module p_5_all_test;

typedef struct {
  logic [11:0] csr_index;  
  logic [31:0] csr_result; 
} csr_t;

typedef struct {
  // INSN
  logic [31:0] pc;     
  logic [31:0] opcode;    
  string asm;        
  // X
  logic [4:0] xreg_index;
  logic [31:0] xreg_result;    
  // F
  logic [4:0] freg_index;
  logic [31:0] freg_result; 
  // V
  logic [4:0] vreg_index;
  logic [127:0] vreg_result;
  // CSR
  csr_t csr_list[8]; // Dynamic array
} instruction_t;
    

    // Associative array to store instructions by order
instruction_t instruction_array [0:87];
    
initial begin
  instruction_array[0]  = '{asm: "auipc   t0, 0x0"                 , pc: 'h00001000  , opcode: 'h00000297  , xreg_index: 'd5       , xreg_result: 'h00001000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[1]  = '{asm: "addi    a1, t0, 32"              , pc: 'h00001004  , opcode: 'h02028593  , xreg_index: 'd11      , xreg_result: 'h00001020, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[2]  = '{asm: "csrr    a0, mhartid"             , pc: 'h00001008  , opcode: 'hf1402573  , xreg_index: 'd10      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[3]  = '{asm: "lw      t0, 24(t0)"              , pc: 'h0000100c  , opcode: 'h0182a283  , xreg_index: 'd5       , xreg_result: 'h80000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[4]  = '{asm: "jr      t0"                      , pc: 'h00001010  , opcode: 'h00028067  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[5]  = '{asm: "nop"                             , pc: 'h80000000  , opcode: 'h00000013  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[6]  = '{asm: "li      ra, 0"                   , pc: 'h80000004  , opcode: 'h00000093  , xreg_index: 'd1       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[7]  = '{asm: "li      sp, 0"                   , pc: 'h80000008  , opcode: 'h00000113  , xreg_index: 'd2       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[8]  = '{asm: "li      gp, 0"                   , pc: 'h8000000c  , opcode: 'h00000193  , xreg_index: 'd3       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[9]  = '{asm: "li      tp, 0"                   , pc: 'h80000010  , opcode: 'h00000213  , xreg_index: 'd4       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[10] = '{asm: "li      t0, 0"                   , pc: 'h80000014  , opcode: 'h00000293  , xreg_index: 'd5       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[11] = '{asm: "li      t1, 0"                   , pc: 'h80000018  , opcode: 'h00000313  , xreg_index: 'd6       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[12] = '{asm: "li      t2, 0"                   , pc: 'h8000001c  , opcode: 'h00000393  , xreg_index: 'd7       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[13] = '{asm: "li      s0, 0"                   , pc: 'h80000020  , opcode: 'h00000413  , xreg_index: 'd8       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[14] = '{asm: "li      s1, 0"                   , pc: 'h80000024  , opcode: 'h00000493  , xreg_index: 'd9       , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[15] = '{asm: "li      a0, 0"                   , pc: 'h80000028  , opcode: 'h00000513  , xreg_index: 'd10      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[16] = '{asm: "li      a1, 0"                   , pc: 'h8000002c  , opcode: 'h00000593  , xreg_index: 'd11      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[17] = '{asm: "li      a2, 0"                   , pc: 'h80000030  , opcode: 'h00000613  , xreg_index: 'd12      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[18] = '{asm: "li      a3, 0"                   , pc: 'h80000034  , opcode: 'h00000693  , xreg_index: 'd13      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[19] = '{asm: "li      a4, 0"                   , pc: 'h80000038  , opcode: 'h00000713  , xreg_index: 'd14      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[20] = '{asm: "li      a5, 0"                   , pc: 'h8000003c  , opcode: 'h00000793  , xreg_index: 'd15      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[21] = '{asm: "li      a6, 0"                   , pc: 'h80000040  , opcode: 'h00000813  , xreg_index: 'd16      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[22] = '{asm: "li      a7, 0"                   , pc: 'h80000044  , opcode: 'h00000893  , xreg_index: 'd17      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[23] = '{asm: "li      s2, 0"                   , pc: 'h80000048  , opcode: 'h00000913  , xreg_index: 'd18      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[24] = '{asm: "li      s3, 0"                   , pc: 'h8000004c  , opcode: 'h00000993  , xreg_index: 'd19      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[25] = '{asm: "li      s4, 0"                   , pc: 'h80000050  , opcode: 'h00000a13  , xreg_index: 'd20      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[26] = '{asm: "li      s5, 0"                   , pc: 'h80000054  , opcode: 'h00000a93  , xreg_index: 'd21      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[27] = '{asm: "li      s6, 0"                   , pc: 'h80000058  , opcode: 'h00000b13  , xreg_index: 'd22      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[28] = '{asm: "li      s7, 0"                   , pc: 'h8000005c  , opcode: 'h00000b93  , xreg_index: 'd23      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[29] = '{asm: "li      s8, 0"                   , pc: 'h80000060  , opcode: 'h00000c13  , xreg_index: 'd24      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[30] = '{asm: "li      s9, 0"                   , pc: 'h80000064  , opcode: 'h00000c93  , xreg_index: 'd25      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[31] = '{asm: "li      s10, 0"                  , pc: 'h80000068  , opcode: 'h00000d13  , xreg_index: 'd26      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[32] = '{asm: "li      s11, 0"                  , pc: 'h8000006c  , opcode: 'h00000d93  , xreg_index: 'd27      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[33] = '{asm: "li      t3, 0"                   , pc: 'h80000070  , opcode: 'h00000e13  , xreg_index: 'd28      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[34] = '{asm: "li      t4, 0"                   , pc: 'h80000074  , opcode: 'h00000e93  , xreg_index: 'd29      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[35] = '{asm: "li      t5, 0"                   , pc: 'h80000078  , opcode: 'h00000f13  , xreg_index: 'd30      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[36] = '{asm: "li      t6, 0"                   , pc: 'h8000007c  , opcode: 'h00000f93  , xreg_index: 'd31      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[37] = '{asm: "lui     t0, 0x12345"             , pc: 'h80000080  , opcode: 'h123452b7  , xreg_index: 'd5       , xreg_result: 'h12345000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[38] = '{asm: "auipc   t1, 0x1"                 , pc: 'h80000084  , opcode: 'h00001317  , xreg_index: 'd6       , xreg_result: 'h80001084, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[39] = '{asm: "auipc   t2, 0x0"                 , pc: 'h80000088  , opcode: 'h00000397  , xreg_index: 'd7       , xreg_result: 'h80000088, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[40] = '{asm: "addi    t2, t2, 16"              , pc: 'h8000008c  , opcode: 'h01038393  , xreg_index: 'd7       , xreg_result: 'h80000098, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[41] = '{asm: "jal     t3, pc + 0x4"            , pc: 'h80000090  , opcode: 'h00400e6f  , xreg_index: 'd28      , xreg_result: 'h80000094, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[42] = '{asm: "nop"                             , pc: 'h80000094  , opcode: 'h00000013  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[43] = '{asm: "li      t4, 68"                  , pc: 'h80000098  , opcode: 'h04400e93  , xreg_index: 'd29      , xreg_result: 'h00000044, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[44] = '{asm: "auipc   t5, 0x0"                 , pc: 'h8000009c  , opcode: 'h00000f17  , xreg_index: 'd30      , xreg_result: 'h8000009c, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[45] = '{asm: "addi    t5, t5, 16"              , pc: 'h800000a0  , opcode: 'h010f0f13  , xreg_index: 'd30      , xreg_result: 'h800000ac, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[46] = '{asm: "jalr    t6, t5, 0"               , pc: 'h800000a4  , opcode: 'h000f0fe7  , xreg_index: 'd31      , xreg_result: 'h800000a8, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[47] = '{asm: "li      t5, 85"                  , pc: 'h800000ac  , opcode: 'h05500f13  , xreg_index: 'd30      , xreg_result: 'h00000055, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[48] = '{asm: "li      s0, 10"                  , pc: 'h800000b0  , opcode: 'h00a00413  , xreg_index: 'd8       , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[49] = '{asm: "li      s1, 20"                  , pc: 'h800000b4  , opcode: 'h01400493  , xreg_index: 'd9       , xreg_result: 'h00000014, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[50] = '{asm: "beq     s0, s0, pc + 8"          , pc: 'h800000b8  , opcode: 'h00840463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[51] = '{asm: "bne     s0, s1, pc + 8"          , pc: 'h800000c0  , opcode: 'h00941463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[52] = '{asm: "blt     s0, s1, pc + 8"          , pc: 'h800000c8  , opcode: 'h00944463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[53] = '{asm: "bge     s1, s0, pc + 8"          , pc: 'h800000d0  , opcode: 'h0084d463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[54] = '{asm: "li      s2, -1"                  , pc: 'h800000d8  , opcode: 'hfff00913  , xreg_index: 'd18      , xreg_result: 'hffffffff, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[55] = '{asm: "bltu    s0, s2, pc + 8"          , pc: 'h800000dc  , opcode: 'h01246463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[56] = '{asm: "bgeu    s2, s0, pc + 8"          , pc: 'h800000e4  , opcode: 'h00897463  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[57] = '{asm: "auipc   a0, 0x0"                 , pc: 'h800000ec  , opcode: 'h00000517  , xreg_index: 'd10      , xreg_result: 'h800000ec, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[58] = '{asm: "addi    a0, a0, 228"             , pc: 'h800000f0  , opcode: 'h0e450513  , xreg_index: 'd10      , xreg_result: 'h800001d0, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[59] = '{asm: "lui     a1, 0xdeadc"             , pc: 'h800000f4  , opcode: 'hdeadc5b7  , xreg_index: 'd11      , xreg_result: 'hdeadc000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[60] = '{asm: "addi    a1, a1, -273"            , pc: 'h800000f8  , opcode: 'heef58593  , xreg_index: 'd11      , xreg_result: 'hdeadbeef, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[61] = '{asm: "sw      a1, 0(a0)"               , pc: 'h800000fc  , opcode: 'h00b52023  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[62] = '{asm: "lw      a2, 0(a0)"               , pc: 'h80000100  , opcode: 'h00052603  , xreg_index: 'd12      , xreg_result: 'hdeadbeef, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[63] = '{asm: "li      a3, 5"                   , pc: 'h80000104  , opcode: 'h00500693  , xreg_index: 'd13      , xreg_result: 'h00000005, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[64] = '{asm: "addi    a4, a3, 10"              , pc: 'h80000108  , opcode: 'h00a68713  , xreg_index: 'd14      , xreg_result: 'h0000000f, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[65] = '{asm: "slti    a5, a3, 10"              , pc: 'h8000010c  , opcode: 'h00a6a793  , xreg_index: 'd15      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[66] = '{asm: "sltiu   a6, a3, 10"              , pc: 'h80000110  , opcode: 'h00a6b813  , xreg_index: 'd16      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[67] = '{asm: "xori    a7, a3, 255"             , pc: 'h80000114  , opcode: 'h0ff6c893  , xreg_index: 'd17      , xreg_result: 'h000000fa, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[68] = '{asm: "ori     s3, a3, 240"             , pc: 'h80000118  , opcode: 'h0f06e993  , xreg_index: 'd19      , xreg_result: 'h000000f5, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[69] = '{asm: "andi    s4, a3, 240"             , pc: 'h8000011c  , opcode: 'h0f06fa13  , xreg_index: 'd20      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[70] = '{asm: "slli    s5, a3, 2"               , pc: 'h80000120  , opcode: 'h00269a93  , xreg_index: 'd21      , xreg_result: 'h00000014, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[71] = '{asm: "srli    s6, s5, 1"               , pc: 'h80000124  , opcode: 'h001adb13  , xreg_index: 'd22      , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[72] = '{asm: "srai    s7, s5, 1"               , pc: 'h80000128  , opcode: 'h401adb93  , xreg_index: 'd23      , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[73] = '{asm: "add     t0, s0, s1"              , pc: 'h8000012c  , opcode: 'h009402b3  , xreg_index: 'd5       , xreg_result: 'h0000001e, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[74] = '{asm: "sub     t1, s1, s0"              , pc: 'h80000130  , opcode: 'h40848333  , xreg_index: 'd6       , xreg_result: 'h0000000a, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[75] = '{asm: "sll     t2, s0, s3"              , pc: 'h80000134  , opcode: 'h013413b3  , xreg_index: 'd7       , xreg_result: 'h01400000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[76] = '{asm: "slt     t3, s0, s1"              , pc: 'h80000138  , opcode: 'h00942e33  , xreg_index: 'd28      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[77] = '{asm: "sltu    t4, s0, s2"              , pc: 'h8000013c  , opcode: 'h01243eb3  , xreg_index: 'd29      , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[78] = '{asm: "xor     t5, s0, s1"              , pc: 'h80000140  , opcode: 'h00944f33  , xreg_index: 'd30      , xreg_result: 'h0000001e, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[79] = '{asm: "srl     t6, s1, s0"              , pc: 'h80000144  , opcode: 'h0084dfb3  , xreg_index: 'd31      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[80] = '{asm: "sra     t5, s2, s0"              , pc: 'h80000148  , opcode: 'h40895f33  , xreg_index: 'd30      , xreg_result: 'hffffffff, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[81] = '{asm: "or      a0, s0, s1"              , pc: 'h8000014c  , opcode: 'h00946533  , xreg_index: 'd10      , xreg_result: 'h0000001e, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[82] = '{asm: "and     a1, s0, s1"              , pc: 'h80000150  , opcode: 'h009475b3  , xreg_index: 'd11      , xreg_result: 'h00000000, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[83] = '{asm: "li      t0, 1"                   , pc: 'h80000154  , opcode: 'h00100293  , xreg_index: 'd5       , xreg_result: 'h00000001, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[84] = '{asm: "auipc   t1, 0x0"                 , pc: 'h80000158  , opcode: 'h00000317  , xreg_index: 'd6       , xreg_result: 'h80000158, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[85] = '{asm: "addi    t1, t1, 40"              , pc: 'h8000015c  , opcode: 'h02830313  , xreg_index: 'd6       , xreg_result: 'h80000180, freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[86] = '{asm: "sw      t0, 0(t1)"               , pc: 'h80000160  , opcode: 'h00532023  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
  instruction_array[87] = '{asm: "j       pc + 0x0"                , pc: 'h80000164  , opcode: 'h0000006f  , xreg_index: 'dx       , xreg_result: 'hx       , freg_index: 'dx       , freg_result: 'hx       , vreg_index: 'dx       , vreg_result: 'hx       , csr_list: '{default: 0}};
end

endmodule